"""add password_hash to users

Revision ID: d2cca46ff3a0
Revises: 757662002dfd
Create Date: 2026-01-12 21:43:29.336284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cca46ff3a0'
down_revision: Union[str, Sequence[str], None] = '757662002dfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1) Add as nullable first (SQLite limitation)
    op.add_column("users", sa.Column("password_hash", sa.String(length=255), nullable=True))

    # 2) Backfill existing rows so old users don't break
    # This is a placeholder. They will NOT be able to login until they reset password (later).
    op.execute("UPDATE users SET password_hash = 'LEGACY_NO_PASSWORD' WHERE password_hash IS NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
